version: '3.9'

services:
  db:
    image: mysql:5.7.33
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - ./backend/.env
    environment:
      MYSQL_DATABASE: short_url
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 2s
      retries: 10


  app:
    build:
      context: ./backend
    container_name: app
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  server:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "81:80"
      - "444:443"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network


  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - app
    environment: 
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules      



networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  frontend_node_modules: